#!/usr/bin/env python
# -*- coding:utf-8 -*-
from optparse import OptionParser, OptionValueError
import markovchains

if __name__=='__main__':
    usage = "usage: %prog filename/dirname [options]"
    parser = OptionParser(usage)
    parser.add_option('-u','--user',action='store',help=u'発言したユーザ')
    (options, args) = parser.parse_args()
    user = ''
    if options.user != None:
        user = options.user
    m = markovchains.MarkovChains()
    print m.make_sentence(user=user)
